# Site settings
title: Tomb of Giants
email: info@tombofgiants.de
description: > # this means to ignore newlines until "baseurl:"
 Wir, Tomb of Giants, sind eine Metal-Band aus Melle in Deutschland.
 Unsere Musik ist vielseitig und deckt viele Sub-Genres des Metal ab. Es ist für jeden etwas dabei.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tombofgiants.de" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
include: ['.htaccess']
exclude: ['assets/js/page-exclusive/slider.js']

# about us page
collections:
  members:
   output: true
   permalink: /band/:path/

gems:
  - octopress-autoprefixer